language: android
android:
  components:
    - tools
    - platform-tools
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
   - ./gradlew build connectedCheck
